altitude:
  data: null
  raw_unit: m
  time_stamp: 0.0
  unit: m
  value: 11.63
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
cadence_speed_device_address:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: FD:DF:0E:4E:76:CF
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
cadence_speed_device_name:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: Lezyne S&C 249
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
data_log_period:
  data: null
  raw_unit: s
  time_stamp: 0.0
  unit: s
  value: 0.85
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
heart_rate:
  data: null
  raw_unit: BPM
  time_stamp: 0.0
  unit: BPM
  value: .nan
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
heart_rate_device_address:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: D6:90:A8:08:F0:E4
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
heart_rate_device_name:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: Tacx HRB 04741
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
log_level:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: DEBUG
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
mean_sea_level_pressure:
  data: null
  raw_unit: Pa
  time_stamp: 0.0
  unit: hPa
  value: 101757.37826355212
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
odometer:
  data: null
  raw_unit: m
  time_stamp: 0.0
  unit: km
  value: 1382.9850000000065
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
pressure:
  data: null
  raw_unit: Pa
  time_stamp: 0.0
  unit: hPa
  value: 101617.18612303348
  value_avg: .nan
  value_max: 101622.25127371603
  value_min: 101616.54429034387
reference_altitude:
  data: null
  raw_unit: m
  time_stamp: 1540155643.1353118
  unit: m
  value: 11.41
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
rider_weight:
  data: null
  raw_unit: kg
  time_stamp: 0.0
  unit: kg
  value: '80.0'
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
speed:
  data: null
  raw_unit: m/s
  time_stamp: 1540638854.585688
  unit: km/h
  value: 0.0
  value_avg: .inf
  value_max: 9.753484162895928
  value_min: .inf
temperature:
  data: null
  raw_unit: C
  time_stamp: 0.0
  unit: C
  value: 22.72
  value_avg: .nan
  value_max: 29.51
  value_min: 19.24
wheel_circumference:
  data: null
  raw_unit: m
  time_stamp: 1540312597.1810174
  unit: mm
  value: 2.105
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
wheel_size:
  data: null
  raw_unit: null
  time_stamp: 0.0
  unit: null
  value: 700X25C
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
write_config_period:
  data: null
  raw_unit: s
  time_stamp: 0.0
  unit: s
  value: 15.0
  value_avg: .nan
  value_max: -.inf
  value_min: .inf
