cadence_speed_device_address:
  force_notification: false
  raw_unit: null
  required_by:
  - ble_sc
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: FD:DF:0E:4E:76:CF
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
cadence_speed_device_name:
  force_notification: false
  raw_unit: null
  required_by:
  - ble_sc
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: null
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
heart_rate_device_address:
  force_notification: false
  raw_unit: null
  required_by:
  - ble_hr
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: D6:90:A8:08:F0:E4
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
heart_rate_device_name:
  force_notification: false
  raw_unit: null
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: null
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
layout_path: layouts/default.yaml
log_level:
  force_notification: false
  raw_unit: null
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: DEBUG
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
odometer:
  force_notification: false
  raw_unit: m
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: km
  units_allowed:
  - m
  - km
  - mi
  value: 500.9900000000002
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
reference_altitude:
  force_notification: false
  raw_unit: m
  required_by:
  - bmp183
  sensor_name: null
  time_stamp: 0.0
  unit: m
  units_allowed:
  - m
  - km
  value: 54.0
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
rider_weight:
  force_notification: false
  raw_unit: kg
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: kg
  units_allowed:
  - kg
  - lb
  value: '80.0'
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
speed:
  force_notification: false
  raw_unit: m/s
  required_by: null
  sensor_name: null
  time_stamp: 1539541698.1684253
  unit: km/h
  units_allowed:
  - m/s
  - km/h
  - mi/h
  value: 0.0
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
temperature:
  force_notification: false
  raw_unit: C
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: C
  units_allowed:
  - C
  - F
  value: 22.33867245629454
  value_avg: .nan
  value_default: null
  value_max: 26.036583890000617
  value_min: 22.02420838559018
wheel_size:
  force_notification: false
  raw_unit: null
  required_by: null
  sensor_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: 700X25C
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
