layout_file:
  force_notification: false
  raw_unit: null
  required_by: null
  reset: false
  plugin_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: []
  value: layouts/weather.yaml
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
log_level:
  force_notification: false
  raw_unit: null
  required_by: null
  reset: false
  plugin_name: null
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: DEBUG
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
reference_altitude:
  force_notification: false
  raw_unit: m
  required_by:
  - bmp280
  reset: false
  plugin_name: null
  time_stamp: 1540155643.1353118
  unit: m
  units_allowed:
  - m
  - km
  value: 11.47
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
temperature:
  force_notification: false
  raw_unit: C
  required_by: null
  reset: false
  plugin_name: null
  time_stamp: 0.0
  unit: C
  units_allowed:
  - C
  - F
  value: 25.36
  value_avg: .nan
  value_default: null
  value_max: 29.51
  value_min: 19.24
