altitude_home: 131.0
altitude_home_units: m
ble_hr_addr: null
ble_hr_name: null
ble_sc_addr: FD:DF:0E:4E:76:CF
ble_sc_name: b'Lezyne S&C 249'
layout_path: layouts/default.yaml
log_level: DEBUG
odometer: 2806.372520048205
odometer_units: km
rider_weight: 78.0
rider_weight_units: kg
ridetime_total: 462.7914369106293
speed_max: 0.0
speed_units: m/s
temperature_units: C
wheel_size: 700x25C
