parameters:
  - name: real_time
    description:  "Time"
  - name: speed
    description:  "Speed"
  - name: cadence
    description:  "Cadence"
  - name: heart_rate
    description:  "Heart RT"
  - name: pressure
    description:  "Pressure"
  - name: pressure_nof
    description:  "Pressure nof"
  - name: temperature
    description:  "Temp"
  - name: altitude
    description:  "Altitude"
  - name: odometer
    description:  "Odometer"
  - name: slope
    description:  "Slope"
