columns:
  - name: real_time
    parameter: real_time
    description:  "Time"
    format: time
  - name: session_time
    parameter: session_time
    description:  "Session"
    format: hhmmss
  - name: speed
    parameter: speed
    description:  "Speed"
  - name: cadence
    parameter: cadence
    description:  "Cadence"
  - name: heart_rate
    parameter: heart_rate
    description:  "Heart RT"
  - name: pressure
    parameter: pressure
    description:  "Pressure"
    format: "%.1f"
  - name: pressure_nof
    parameter: pressure_nof
    description:  "Pressure nof"
  - name: temperature
    parameter: temperature
    description:  "Temp"
  - name: altitude
    parameter: altitude
    description:  "Altitude"
  - name: odometer
    parameter: odometer
    description:  "Odometer"
  - name: slope
    parameter: slope
    description:  "Slope"
    format: '%.3f'
