cadence_speed_device_address:
  force_notification: false
  raw_unit: null
  required_by:
  - ble_sc
  - ble_sc
  sensor_name: config
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: FD:DF:0E:4E:76:CF
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
cadence_speed_device_name:
  force_notification: false
  raw_unit: null
  required_by: &id001
  - ble_sc
  sensor_name: ble_sc
  time_stamp: 0.0
  unit: null
  units_allowed: &id002 []
  value: null
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
heart_rate_device_address:
  force_notification: false
  raw_unit: null
  required_by:
  - ble_hr
  - ble_hr
  sensor_name: config
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: D6:90:A8:08:F0:E4
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
heart_rate_device_name:
  force_notification: false
  raw_unit: null
  required_by: *id001
  sensor_name: config
  time_stamp: 0.0
  unit: null
  units_allowed: *id002
  value: null
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
layout_path: layouts/default.yaml
log_level: DEBUG
odometer:
  force_notification: false
  raw_unit: m
  required_by: null
  sensor_name: compute
  time_stamp: 0.0
  unit: km
  units_allowed:
  - m
  - km
  - mi
  value: 319.0
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
reference_altitude:
  force_notification: false
  raw_unit: m
  required_by:
  - bmp183
  sensor_name: config
  time_stamp: 0.0
  unit: m
  units_allowed:
  - m
  - km
  value: 54.0
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
rider_weight:
  force_notification: false
  raw_unit: kg
  required_by: null
  sensor_name: config
  time_stamp: 0.0
  unit: kg
  units_allowed:
  - kg
  - lb
  value: '80.0'
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
speed:
  force_notification: false
  raw_unit: m/s
  required_by: null
  sensor_name: compute
  time_stamp: 0.0
  unit: km/h
  units_allowed:
  - m/s
  - km/h
  - mi/h
  value: null
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
temperature:
  force_notification: false
  raw_unit: C
  required_by: null
  sensor_name: bmp183
  time_stamp: 0.0
  unit: C
  units_allowed:
  - C
  - F
  value: 10
  value_avg: .nan
  value_default: null
  value_max: 10
  value_min: 10
wheel_size:
  force_notification: false
  raw_unit: null
  required_by: null
  sensor_name: config
  time_stamp: 0.0
  unit: null
  units_allowed: null
  value: 700x25C
  value_avg: .nan
  value_default: null
  value_max: -.inf
  value_min: .inf
