columns:
  - name: date
    parameter: real_time
    description:  "Date"
    format: date

  - name: time
    parameter: real_time
    description:  "Time"
    format: time

  - name: pressure
    parameter: pressure
    description:  "Pressure"
    format: "%.1f"

  - name: mean_sea_level_pressure
    parameter: mean_sea_level_pressure
    description:  "MSL Pressure"

  - name: temperature
    parameter: temperature
    description:  "Temp"

  - name: altiture
    parameter: altitude
    description:  "Altitude"
